name: wb_warehouse
description: App that makes it easy to work with WB Partners.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_annotation: ^4.8.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  flutter_lints: ^2.0.0
  dart_code_metrics: ^5.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
