name: wb_warehouse
description: App that makes it easy to work with WB Partners.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  auto_route: ^7.8.4
  animated_splash_screen: ^1.3.0
  cupertino_icons: ^1.0.2
  dio: ^5.0.0
  elementary: ^3.0.0
  enum_to_string: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  provider: ^6.0.5
  intl: ^0.18.1
  json_annotation: ^4.8.1
  surf_logger: ^1.1.0
  rxdart: ^0.27.7
  shared_preferences: ^2.0.18
  quiver: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  flutter_lints: ^3.0.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/pictures/

flutter_icons:
  windows:
    generate: true
    image_path: "assets/icons/wb_warehouse_app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/wb_warehouse_app_icon.png"
