name: wb_warehouse
description: App that makes it easy to work with WB Partners.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.6
  auto_route: ^5.0.4
  cupertino_icons: ^1.0.2
  dio: ^5.0.0
  elementary: ^2.0.0
  flutter_launcher_icons: ^0.12.0
  provider: ^6.0.5
  intl: ^0.17.0
  json_annotation: ^4.8.0
  surf_logger: ^1.1.0
  rxdart: ^0.27.7
  quiver: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  flutter_lints: ^2.0.0
  dart_code_metrics: ^5.6.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/

flutter_icons:
  windows:
    generate: true
    image_path: "assets/icons/wb_warehouse_app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/wb_warehouse_app_icon.png"